meslekler=["Aşçı","Aşçıbaşı","Aile hekimi","Aktar","Aktör","Aktris","Akustikçi","Albay","Ambalajcı","Ambulans şoförü",
           "Amiral","Anahtarcı","Anestezi uzmanı","Araştırmacı","Arıcı","Arkeolog","Asker","Avcı","Avukat",
           "Ayakkabıcı","Bahçıvan","Bakan","Bakıcı","Bakkal","Balıkçı","Balerin","Bankacı","Barmen","Basketbolcu",
           "Başbakan","Başkan","Başkomiser","Belediye başkanı","Berber","Besteci","Bilgisayar mühendisi",
           "Bilim insanı","Borsacı","Bulaşıkçı","Bebek bakıcısı","Camcı","Cerrah","Cellat","Cumhurbaşkanı","Çaycı",
           "Çevirmen","Çiçekçi","Çiftçi","Çilingir","Çitçi","Çoban","Çocuk doktoru","Çöpçü","Çırak","Dadı",
           "Dalgıç","Danışman","Dansöz","Dedektif","Denizci","Diplomat","Diş hekimi","Diyetisyen","Doktor","Dondurmacı",
           "Diş teknisyeni","Dansçı","Eczacı","Editör","Ekonomist","Elektrik mühendisi","Elektrikçi","Emlakçı",
           "Endüstri mühendisi","Esnaf","Ev hanımı","Fırıncı","Figüran","Film yönetmeni","Filozof","Fotoğrafçı",
           "Futbolcu","Gardiyan","Galerici","Garson","Gazeteci","General","Gıda mühendisi","Göz doktoru","Gözetmen",
           "Gözlükçü","Haberci","Hakem","Hamal","Harita mühendisi","Hattat","Hemşire","Heykeltıraş","Hırdavatçı",
           "Hizmetçi","Hostes","Hurdacı","Irgat","İcra memuru","İç mimar","İktisatçı","İlahiyatçı","İmam",
           "İnşaat mühendisi","İnşaatçı","İşçi","İtfaiyeci","Jeofizik mühendisi","Jeoloji mühendisi","Jimnastikçi",
           "Jokey","Kabin görevlisi","Kameraman","Kamyoncu","Kapıcı","Kaportacı","Kaptan","Kardiyolog","Karikatürist",
           "Kasap","Kasiyer","Kat görevlisi","Kayıkçı","Kaymakam","Kaynakçı","Kebapçı","Kırtasiyeci","Kimyager",
           "Kimya mühendisi","Koleksiyoncu","Komedyen","Komiser","Kozmolog","Köşe yazarı","Kuaför","Kurye","Kuyumcu",
           "Kütüphaneci","Laborant","Madenci","Makinist","Makine mühendisi","Manav","Manken","Marangoz","Matador",
           "Matbaacı","Memur","Menajer","Mevsimlik işçi","Milletvekili","Mimar","Mobilyacı","Model","Muhabir","Muhafız",
           "Muhasebeci","Muhtar","Mübaşir","Müdür","Müezzin","Müfettiş","Müşavir","Mühendis","Müneccim","Müsteşar",
           "Müteahhit","Müzisyen","Nakliyeci","Nalbant","Nalbur","Oduncu","Okçu","Okul müdürü","Orgeneral",
           "Orman mühendisi","Otelci","Oto tamircisi","Overlokçu","Oyuncu","Oyuncakçı","Öğretmen","Özel şoför",
           "Palyaço","Pandomimci","Pansiyoncu","Paralı asker","Patolog","Peyzaj mimarı","Pilot","Piyade",
           "Piyango satıcısı","Piyanist","Polis memuru","Polis şefi","Pompacı","Postacı","Profesör","Psikiyatr",
           "Psikolog","Paramedik","Rehber","Reklamcı","Rektör","Ressam","Sahil koruma","Sarraf","Satış elemanı","Savcı",
           "Sekreter","Senarist","Serbest muhasebeci","Seyis","Sigortacı","Sihirbaz","Simitçi","Siyasetçi","Sosyolog",
           "Spiker","Su tesisatçısı","Subay","Suflör","Sunucu","Sünnetçi","Şair","Şarkıcı","Şoför","Şehir Plancısı",
           "Şıracı","Taksici","Tarihçi","Tasarımcı","Tefeci","Teğmen","Tekniker","Teknisyen","Telefon operatörü",
           "Tellal","Temizlikçi","Terapist","Tercüman","Terzi","Tezgahtar","Tesisatçı","Tornacı","Turizmci",
           "Tuhafiyeci","Turşucu","Uçuş teknisyeni","Ustabaşı","Üretici","Ürolog","Vaiz","Vali","Vergi müfettişi",
           "Veteriner","Veznedar","Video editörü","Vinç operatörü","Vale","Yarbay","Yardımcı hakem","Yardımcı pilot",
           "Yargıç","Yatırım uzmanı","Yayıncı","Yazar","Yazılım mühendisi","Yelkenci","Yeminli tercüman","Yönetici",
           "Yüzücü","Yönetmen","Zabıta","Zoolog","Ziraat mühendisi"]